GPUS: [0]
WORKERS: 4
PRINT_FREQ: 100

DATASET:
  DATASET: avenue
  ROOT: '/content/astnet/ASTNet/datasets'
  NUM_FRAMES: 7
  FRAME_STEPS: 2
  LOWER_BOUND: 100

TRAIN:
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME: true
  OPTIMIZER: 'adam'
  LR_TYPE: 'multistep'
  LR: 0.0002
  LR_STEP: [60, 80]

TEST:
  BATCH_SIZE_PER_GPU: 1

MODEL:
  NAME: 'wrn38_layer6'
  INIT_WEIGHTS: true
  PRETRAINED: '../../datasets/seg_weights/wider_resnet38.pth.tar'
  IMAGE_SIZE:
    - 192
    - 320
  MEMORY_SIZE: 7
  ENCODED_FRAMES: 6
  DECODED_FRAMES: 0
  EXTRA:
    FINAL_CONV_KERNEL: 3
